### ISSUE TITLE
What are the purposes of Java and Python codes?

### ISSUE THREAD

**Issue by pjgao** [shujiehan/StreamDFP#2]
Hello, The repository contains two parts: Java and Python. And I found both have `sim.run` and `inspect`.
Why do you use two languages to do this? What's the difference between them?

**Comment by shujiehan** [comment]
> Hello, The repository contains two parts: Java and Python. And I found both have `sim.run` and `inspect`.
> Why do you use two languages to do this? What's the difference between them?

The Python part is for data preprocessing and the java part is for training and prediction.
If you'd like to run StreamDFP, you need to first run with Python for preprocessing and then run with Java.
You may refer to [our paper](http://www.cse.cuhk.edu.hk/~pclee/www/pubs/icdcs20.pdf) to see implementation details (Section IV-G).
